### ISSUE TITLE
Bags are now against the right edge of screen.

### ISSUE THREAD

**Issue by zaphon** [Nevcairiel/Bartender4#120]
With the latest version of Bartender4 the bags have now repositioned themselves to the far right side of the screen. Prior versions as long as you have the two right hand bars enabled in the default UI the bags would be to the left of them, now it shows them on top of them. I'm going to review the changes to try and figure out what changed.

**Comment by zaphon** [comment]
Looking into this, it has to do with how you're hiding the default bars now, as the bag position is based off a call to EditModeUtil:GetRightActionBarWidth() (which returns all kinds of funky values with Bartender4 loaded which is why bags sometimes are in middle of screen and sometimes off the screen). I tried actually overriding that function and returning the proper value for my screen size, which does work, but it severely taints things. I'm going to keep looking at it.

**Comment by Nevcairiel** [comment]
There is something weird going on with Edit Mode and positioning, because just hiding the bars should not screw with their position data - and its also somehow a transient failure that fixes itself shortly after.

**Comment by grumple-ait** [comment]
Yeah, I've been using Bartender forever, but I got used to the right hand bars back in Vanilla so I do reposition them a bit, but they're effectively in the same position. I used Bartender to basically stack 4 bars in the middle on the bottom, which I couldn't recreate with the new Blizz UI because I used bar6 as my top bar (which they don't let you use, instead they added new bars), and I didn't feel like redoing those 12 buttons across 100+ characters (I'm an addicted altoholic).

And yeah something funky goes on with GetRightActionBarWidth, as it returns all kinds of funky info with Bartender loaded until I go in and out of edit mode (just open it and close it is enough to fix it). But whatever you changed in the last release has caused the width of the bars to come back as basically 1 pixel for each bar (as I get 2 with bartender loaded, approximately 80 without it loaded) It doesn't make a lot of sense.

And looking at other addons that can move stuff, evidently the bags are the one thing they can't seem to move reliably. Everyone recommends me using an alternative bag addon, but they all combine the bags which I don't like.

Either way, thanks for responding. I'll keep looking into this as well to see what I can find.
