### ISSUE TITLE
wotlk: Pet bar doesn't respond consistently with keybindings

### ISSUE THREAD

**Issue by callmeron** [Nevcairiel/Bartender4#143]
When using the keybinds for the pet bar, they don't work consistently. This is the default pet bar, and default keybindings. 

This behavior does not exist when bartender4 is disabled.

**Comment by bmccord** [comment]
I can confirm this bug

**Comment by TheButton00** [comment]
I also have this bug

**Comment by commitedman** [comment]
issue has been reported also here: https://www.wowace.com/projects/bartender4/issues/2102

**Comment by Nevcairiel** [comment]
Keybindings and execution of the buttons are managed by Blizzard, since it requires secure functionality. Addons have no influence on when and how the execution works.

It sounds to me like Blizzard screwed up handling of keybindings with modifiers, in particular when that modifier is CTRL which is usually the "pickup action" modifier.

**Comment by commitedman** [comment]
copy pasting from wowace forum, not sure which issue system you prefer, please let me know.

i am not sure what is going on but the issue can be easily tested with a hunter or lock:

"toggle actions on key press instead of release" is off / unchecked and bt4 addon is on

test performed : target an enemy and press attack-pet action
CTRL + 1 : works only if CTRL and 1 are released at the same time

change keybinding to 4: works as intended
change keybinding to ALT+1: works only if ALT and 1 are released at the same time
change keybinding to SHIFT+1: works only if works only if SHIFT and 1 are released at the same time
change keybinding to SHIFT+1 in bt4 keybinding section: works only if works only if SHIFT and 1 are released at the same time

 when bt4 is disabled:
CTRL + 1 : works by pressing and releasing CTRL and 1 at the same time or at different times.

**Comment by tygore587** [comment]
Can confirm the problem. Also /petattack in any macro doesn't work anymore.

**Comment by callmeron** [comment]
> Keybindings and execution of the buttons are managed by Blizzard, since it requires secure functionality. Addons have no influence on when and how the execution works.
> 
> It sounds to me like Blizzard screwed up handling of keybindings with modifiers, in particular when that modifier is CTRL which is usually the "pickup action" modifier.

@Nevcairiel Regardless of who's at fault, given the assessment of the behavior differences identified in https://github.com/Nevcairiel/Bartender4/issues/143#issuecomment-1399288848 and another action bar addon (Dominoes) I tried to repro (but couldn't), do you think it is possible to get this bug fixed? Or is this deemed a "Not to be fixed" issue?

**Comment by stepofway** [comment]
![изображение](https://user-images.githubusercontent.com/14864400/213912662-fbcf7aad-1e79-4df1-b146-d1da75f27ce6.png)
**Temporary solution**. Using empty bar (bar #2 in screenshot) with standard macro (/petattack, /petfollow, /petstay etc.). And keybinding with bartender4 hover utility.

**Comment by stepofway** [comment]
> copy pasting from wowace forum, not sure which issue system you prefer, please let me know.
> 
> i am not sure what is going on but the issue can be easily tested with a hunter or lock:
> 
> "toggle actions on key press instead of release" is off / unchecked and bt4 addon is on
> 
> test performed : target an enemy and press attack-pet action CTRL + 1 : works only if CTRL and 1 are released at the same time
> 
> change keybinding to 4: works as intended change keybinding to ALT+1: works only if ALT and 1 are released at the same time change keybinding to SHIFT+1: works only if works only if SHIFT and 1 are released at the same time change keybinding to SHIFT+1 in bt4 keybinding section: works only if works only if SHIFT and 1 are released at the same time
> 
> when bt4 is disabled: CTRL + 1 : works by pressing and releasing CTRL and 1 at the same time or at different times.

**On bindings ctrl+1, shift+1, alt+1 on pet spells and enabled bt4:**
If pressing binded keys at same time or different time and wait some seconds and release buttons at the same time - bindings not works.
**Bindings works normally only if time between pressing and releasing < halfsecond.**

**Comment by callmeron** [comment]
> ![изображение](https://user-images.githubusercontent.com/14864400/213912662-fbcf7aad-1e79-4df1-b146-d1da75f27ce6.png) **Temporary solution**. Using empty bar (bar #2 in screenshot) with standard macro (/petattack, /petfollow, /petstay etc.). And keybinding with bartender4 hover utility.

Yeah, this is what I did. Kinda ghetto.

**Comment by callmeron** [comment]
Just tried [4.14.5](https://www.wowace.com/projects/bartender4/files/4359223) locally, and it seems to resolve the problem. Thanks!
