### ISSUE TITLE
[Feature Request] Hotkeys or macro commands to show/hide individual bars

### ISSUE THREAD

**Issue by Jakobud** [Nevcairiel/Bartender4#15]
I'm looking for a while to show/hide individual bars using macros. I have some bars I use only part of the time and don't need them visible all the time. Being able to quickly toggle them would be nice. I would think this would be a pretty straightforward command to add.

**Comment by Nevcairiel** [comment]
You can already do this through the chat configuration interface

ie. something like this
/bartender bars 1 visibility always

This will toggle visibility of bar 1
Note that you cannot do this in combat, and thats also unfixable.

**Comment by Jakobud** [comment]
Oh I had no clue. Where is the documentation on this? What all can you do with these commands?

**Comment by Nevcairiel** [comment]
You can do all the same as you can through the UI config.
Just type eg. "/bartender bars" and it'll list all sub-sections, and you can navigate your way through just like in the UI

(note that some options may seem awkward from the chat interface, that is because it was primarily designed for a decent UI interface, and when you lack some of the explanatory labels and whatnot,  options may seem odd, or even backwards)
