### ISSUE TITLE
10.1 Queue status Bar - eye often goes to its default position

### ISSUE THREAD

**Issue by Nillx** [Nevcairiel/Bartender4#166]
Noticed that since 10.1 the LFG eye often goes down in the right bottom bar (default position) and to fix that i have to open bartender settings and disable/enable the eye to switch to the spot i chose.

**Comment by zaphon** [comment]
I just switched back to BT4 after using the built in new UI since 10.0 and I have a similar issue. But the LFG eye keeps going underneath my action bars (which are centered on the bottom) every time I go into a battleground. Disabling / Enabling moves it back, but it's odd as I was like why is it moving at all. That's not the location I have it set to in edit mode either.

**Comment by Nillx** [comment]
This is still happening. Currently using a different addon (Edit Mode Expanded) that lets me move the eye and its not moving down randomly.

**Comment by Nevcairiel** [comment]
This should hopefully be fixed in the latest version
