### ISSUE TITLE
Hiding "Blizzard Art Bar" does not hide Zone Ability Bar art, no other option to do so

### ISSUE THREAD

**Issue by astradamus** [Nevcairiel/Bartender4#30]
The artwork on these things is absolutely ridiculous.

![image](https://user-images.githubusercontent.com/12521094/89391837-94183980-d6bd-11ea-8ee5-4482120ee9be.png)

**Comment by Nevcairiel** [comment]
Its not supposed to do that. Bartender just lets you move it, there are no plans to change how it works.

**Comment by astradamus** [comment]
Why does Bartender let us remove the Blizzard Art Bar at all then? How are the functionalities different? Either both belong, or neither?

**Comment by Nevcairiel** [comment]
The main bottom art is actually always being removed, because its tightly ingrained with the default action bar functionality, and removing the whole thing is the only logical way to replace the entire default action bars, the Blizzard Art Bar is a manual re-creation of the existing artwork for people that like having it - it does not allow the original to return.

If one were to translate that to the zone ability button, it would mean that the button itself would have to be entirely re-created without the artwork, or the artwork carefully separated from the button. But considering an easier solution is to simply drag the button to an action bar and thus stop it from showing up entirely, the effort involved with that was never worth the minimal use - especially considering at this point its only for legacy content one might spend a few hours leveling in at most.

**Comment by astradamus** [comment]
BFA WQs put abilities there with similar wacky artwork, but I get what you mean. As usual with programming the correct answer is, "That's not worth the effort to implement" which is fine :P  Thanks for the tip on dragging it off, didn't realize that was an option.

**Comment by Nevcairiel** [comment]
Actually WQs and boss abilities are more likely in the "Extra Action Bar", I have no clue why Blizzard made a new one for the zone buttons - maybe specifically due to the dragging off behavior. Of course it suffers from the same graphical bloat sometimes.
