### ISSUE TITLE
Frame Level for extraAbilityContainer

### ISSUE THREAD

**Issue by Numorphan** [Nevcairiel/Bartender4#38]
With the pre-patch, the extraAbilityContainer, when using things that would go into the old extraActionButton, blocks nearby frames in a way that it didn't before. Prior, the "artwork" part of the button would be underneath other frames, allowing you to click on buttons in those frames just fine. Now, those buttons are blocked, even if the artwork is hidden. It would be highly appreciated if there was a way to put this container underneath other bars. (Also, I see you added frame levels for example the status bar, but I don't see how to change this in-game, there doesn't seem to be an option for it, at least that I could see.)

**Comment by Nevcairiel** [comment]
I've added the ability for myself to control the frame levels of the bars in relation to each other, because certain ordering should be maintained - its not meant to be edited by users.

I have however lowered the extra action bar now so that it sits below the normal action buttons again and won't obscur them. This is exactly the thing that mechanic was introduced for, previously it mostly just worked by sheer luck.
