### ISSUE TITLE
Request: Allow blacklisting/hiding of stance buttons

### ISSUE THREAD

**Issue by Desik** [Nevcairiel/Bartender4#69]
In WoW Classic/TBC/SoM some stance buttons are useless, some examples are Resistance Auras buttons for Paladins, Aquatic/Travel form for Druids (Most people macro these together) and single stance buttons like Shadowform

Thanks in advance

**Comment by Nevcairiel** [comment]
No plans for that. The Stance Bar mirrors the Blizzard Stance bar, and shall continue to do so, as it has since the game was actually in Vanilla (and this was Bartender 1 and 2).

If you want a customized bar, you could disable the stance bar and instead use an action bar where you put the appropriate stances on to cast from there.
