### ISSUE TITLE
Keybinds are not showing up on all bars except "1" even though they show on default blizz bars

### ISSUE THREAD

**Issue by addonaddict** [Nevcairiel/Bartender4#73]
Hi, is there any reason default-set keybinds dont show up on all bars except bar 1?
Show hotkeys is enabled in the settings for these bars.
If you need to re-set these keybinds again in addon settings - can we make it so by default bars grab the default-set blizzard hotkeys? And if that doesnt work, can always set our own keybinds?
Feels off having to set keybinds in 2 different locations just so the hotkey text matches.

Thanks

Bartender - no keybinds showing
![image](https://user-images.githubusercontent.com/73442541/159211393-69400d33-cf16-4ed4-9605-595421a245e8.png)

Default:
![image](https://user-images.githubusercontent.com/73442541/159211279-6cc7a12b-17dd-4ef3-99c1-be78b0a1cda1.png)

**Comment by Nevcairiel** [comment]
Bartender only takes over the bar 1 keybindings, if you want other bindings to show, you need to rebind to the bartender buttons specifically.

This has been decided upon ages ago because the association between the numbered Bartender bars and the bars in the default UI based on their location is very confusing to many players, so having them rebind once when building up their UI with Bartender was the easiest to get full understanding of how it all works.
