### ISSUE TITLE
(Minor) Action bar number's don't align with blizzard UI

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [Nevcairiel/Bartender4#97]
It's a minor thing but for example blizzard action bar 2 is bartender bar 6 and blizzard bar 3 is bartender bar 5. What I mean is that if you put the spells on blizzard's action bars they will show up on different bartender action bars. I usually keep the same layout between addons and blizz UI, in the case something breaks with the addon and I have to disable it until fixed.

**Comment by Nevcairiel** [comment]
Bartender has been using numbered bars for over a decade, when Blizzard still named them arbitrary names like "bottom left" and "bottom right". Unfortunately when Blizzard change the names to have numbers, they of course didn't use the same numbers.

I'm not going to rename the Bartender bars, because that would just be confusing to long-time users. But maybe I can put a note somewhere how they align.

**Comment by KonstantinosKoubetsos** [comment]
Ok makes sense.

**Comment by Nevcairiel** [comment]
Actually I have been thinking about how to convey this, and 10.0/DF might be a good time to break with tradition and just use their names. I had already done some steps towards that by renaming the old 7-10 to Class Bars 1-4

So in the future Bars 1-8 should match Blizzards Bars, with Bartender offering an additional Bonus Bar (Previously known as #2), and the Class Bars 1-4
